name: 'Asana Git'
description: 'Asana Github Actions'
inputs:
  asana-pat:
    description: 'Asana Public Access Token.'
    required: true
  comment-pr-link:
    description: 'Set to true to add a comment with the pull request link to the asana task.'
    required: false
  target-section:
    description: 'Provide the name of an Asana projects section or column where you want to move the task.'
    required: false
  trigger-phrase:
    description: 'Prefix before the task i.e ASANA TICKET: https://app.asana.com/1/2/3'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
